# Generated by Django 3.0.7 on 2020-06-14 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('date', models.DateField(verbose_name='public_date')),
                ('is_accepted', models.BooleanField(verbose_name='is_accepted')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='value')),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=10, verbose_name='value')),
            ],
        ),
        migrations.CreateModel(
            name='WebDemo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('code', models.TextField(verbose_name='code')),
                ('date', models.DateField(verbose_name='public_date')),
                ('is_accepted', models.BooleanField(verbose_name='is_accepted')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Article')),
            ],
        ),
    ]
