# Generated by Django 3.0.7 on 2020-06-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bday',
            field=models.DateField(null=True, verbose_name='bday'),
        ),
    ]
