# Generated by Django 3.0.7 on 2020-06-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200611_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bday',
            field=models.DateField(blank=True, null=True, verbose_name='bday'),
        ),
    ]
